"""empty message

Revision ID: 2b0bbfcc97d1
Revises: c9dd0c74433e
Create Date: 2020-07-10 12:21:48.688839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b0bbfcc97d1'
down_revision = 'c9dd0c74433e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'id_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_token', sa.VARCHAR(length=1000), nullable=True))
    # ### end Alembic commands ###
