"""comment table

Revision ID: 3185ff6bd10f
Revises: f0b74ad9c0b3
Create Date: 2020-05-23 02:46:49.889562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3185ff6bd10f'
down_revision = 'f0b74ad9c0b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('commentid', sa.Integer(), nullable=False),
    sa.Column('postid', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['postid'], ['post.postid'], ),
    sa.PrimaryKeyConstraint('commentid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
