"""empty message

Revision ID: 674975520d24
Revises: 3185ff6bd10f
Create Date: 2020-07-09 02:59:37.525973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674975520d24'
down_revision = '3185ff6bd10f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('depart_time', sa.DateTime(), nullable=True),
    sa.Column('origin', sa.String(length=300), nullable=True),
    sa.Column('destination', sa.String(length=300), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id_token', sa.String(length=1000), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_token')
    )
    op.create_table('rides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=300), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id_token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    op.drop_table('comment')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('postid', sa.INTEGER(), nullable=False),
    sa.Column('userid', sa.INTEGER(), nullable=False),
    sa.Column('created', sa.TIME(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('body', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('postid')
    )
    op.create_table('comment',
    sa.Column('commentid', sa.INTEGER(), nullable=False),
    sa.Column('postid', sa.INTEGER(), nullable=False),
    sa.Column('comment', sa.VARCHAR(), nullable=True),
    sa.Column('created', sa.TIME(), nullable=True),
    sa.ForeignKeyConstraint(['postid'], ['post.postid'], ),
    sa.PrimaryKeyConstraint('commentid')
    )
    op.create_table('user',
    sa.Column('userid', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=60), nullable=True),
    sa.Column('phone', sa.INTEGER(), nullable=True),
    sa.Column('address', sa.VARCHAR(length=60), nullable=True),
    sa.Column('password', sa.VARCHAR(length=300), nullable=True),
    sa.PrimaryKeyConstraint('userid')
    )
    op.drop_table('rides')
    op.drop_table('users')
    op.drop_table('trips')
    # ### end Alembic commands ###
