"""empty message

Revision ID: b5e69c27f276
Revises: c6d656ce8a84
Create Date: 2020-07-10 16:36:32.356606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e69c27f276'
down_revision = 'c6d656ce8a84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('id_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_token', sa.VARCHAR(length=1000), nullable=True))

    # ### end Alembic commands ###
