"""empty message

Revision ID: d49b4c2d9766
Revises: 2b0bbfcc97d1
Create Date: 2020-07-10 16:33:51.390639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd49b4c2d9766'
down_revision = '2b0bbfcc97d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'id_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_token', sa.VARCHAR(length=1000), nullable=True))
    # ### end Alembic commands ###
